// <auto-generated />
using System;
using ImportCostPro.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImportCostPro.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604135829_FixedMonedaLocal")]
    partial class FixedMonedaLocal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImportCostPro.Core.Entities.CategoriaArancelaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<decimal>("PorcentajeArancel")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasArancelarias");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.ConfiguracionImpuestos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PorcentajeITBIS")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PorcentajeTasaServicioAduanal")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionesImpuestos");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.DetalleOrdenImportacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("OrdenImportacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenImportacionId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesOrdenImportacion");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.GastoImportacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetodoDistribucion")
                        .HasColumnType("int");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrdenImportacionId")
                        .HasColumnType("int");

                    b.Property<int>("TipoGasto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonedaId");

                    b.HasIndex("OrdenImportacionId");

                    b.ToTable("GastosImportacion");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Importador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("RNC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Importadores");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Moneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoISO")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsMonedaLocal")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Monedas");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.OrdenImportacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImportadorId")
                        .HasColumnType("int");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImportadorId");

                    b.HasIndex("MonedaId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("OrdenesImportacion");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoISO")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoriaArancelariaId")
                        .HasColumnType("int");

                    b.Property<int?>("ImportadorId")
                        .HasColumnType("int");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<decimal>("Precio")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaArancelariaId");

                    b.HasIndex("ImportadorId");

                    b.HasIndex("MonedaId");

                    b.HasIndex("PaisId");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.TasaCambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Tasa")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("MonedaId");

                    b.ToTable("TasasCambio");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.DetalleOrdenImportacion", b =>
                {
                    b.HasOne("ImportCostPro.Core.Entities.OrdenImportacion", "OrdenImportacion")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenImportacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Core.Entities.Producto", "Producto")
                        .WithMany("DetallesOrdenImportacion")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenImportacion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.GastoImportacion", b =>
                {
                    b.HasOne("ImportCostPro.Core.Entities.Moneda", "Moneda")
                        .WithMany("GastosImportacion")
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Core.Entities.OrdenImportacion", "OrdenImportacion")
                        .WithMany("Gastos")
                        .HasForeignKey("OrdenImportacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moneda");

                    b.Navigation("OrdenImportacion");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.OrdenImportacion", b =>
                {
                    b.HasOne("ImportCostPro.Core.Entities.Importador", "Importador")
                        .WithMany("OrdenesImportacion")
                        .HasForeignKey("ImportadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Core.Entities.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Core.Entities.Proveedor", "Proveedor")
                        .WithMany("OrdenesImportacion")
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Importador");

                    b.Navigation("Moneda");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Producto", b =>
                {
                    b.HasOne("ImportCostPro.Core.Entities.CategoriaArancelaria", "CategoriaArancelaria")
                        .WithMany()
                        .HasForeignKey("CategoriaArancelariaId");

                    b.HasOne("ImportCostPro.Core.Entities.Importador", null)
                        .WithMany("Productos")
                        .HasForeignKey("ImportadorId");

                    b.HasOne("ImportCostPro.Core.Entities.Moneda", "Moneda")
                        .WithMany("Productos")
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Core.Entities.Pais", "Pais")
                        .WithMany("Productos")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoriaArancelaria");

                    b.Navigation("Moneda");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.TasaCambio", b =>
                {
                    b.HasOne("ImportCostPro.Core.Entities.Moneda", "Moneda")
                        .WithMany("TasasCambio")
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moneda");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Importador", b =>
                {
                    b.Navigation("OrdenesImportacion");

                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Moneda", b =>
                {
                    b.Navigation("GastosImportacion");

                    b.Navigation("Productos");

                    b.Navigation("TasasCambio");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.OrdenImportacion", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Gastos");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Pais", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Producto", b =>
                {
                    b.Navigation("DetallesOrdenImportacion");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Proveedor", b =>
                {
                    b.Navigation("OrdenesImportacion");
                });
#pragma warning restore 612, 618
        }
    }
}
