// <auto-generated />
using System;
using ImportCostPro.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ImportCostPro.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260906221144_CalculoOficialYMargen")]
    partial class CalculoOficialYMargen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ImportCostPro.Core.Entities.CategoriaArancelaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AplicaITBIS")
                        .HasColumnType("bit");

                    b.Property<bool>("AplicaImpuestoSelectivo")
                        .HasColumnType("bit");

                    b.Property<string>("CodigoArancelario")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<decimal>("PorcentajeArancel")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PorcentajeImpuestoSelectivo")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasArancelarias");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.ConfiguracionImpuestos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("PorcentajeITBIS")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PorcentajeTasaServicioAduanal")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.ToTable("ConfiguracionesImpuestos");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.DetalleOrdenImportacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("MargenDeseado")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("OrdenImportacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrdenImportacionId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesOrdenImportacion");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.DetalleResultadoLandedCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Arancel")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CIF")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoTotalImportado")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("CostoUnitarioImportado")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FOBLocal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FOBOriginal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FleteAsignado")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GastosLocalesAsignados")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ITBIS")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ImpuestoSelectivo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MargenDeseado")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PorcentajeArancel")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PorcentajeImpuestoSelectivo")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PrecioVentaSugerido")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("ResultadoLandedCostId")
                        .HasColumnType("int");

                    b.Property<decimal>("SeguroAsignado")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TasaServicioAduanal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("ResultadoLandedCostId");

                    b.ToTable("DetallesResultadoLandedCost");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.GastoImportacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetodoDistribucion")
                        .HasColumnType("int");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrdenImportacionId")
                        .HasColumnType("int");

                    b.Property<int>("TipoGasto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MonedaId");

                    b.HasIndex("OrdenImportacionId");

                    b.ToTable("GastosImportacion");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Importador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("RNC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Importadores");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Moneda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoISO")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EsMonedaLocal")
                        .HasColumnType("bit");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Simbolo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Monedas");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.OrdenImportacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("datetime2");

                    b.Property<int>("ImportadorId")
                        .HasColumnType("int");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int");

                    b.Property<int>("ProveedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ImportadorId");

                    b.HasIndex("MonedaId");

                    b.HasIndex("ProveedorId");

                    b.ToTable("OrdenesImportacion");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoISO")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Alto")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Ancho")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoriaArancelariaId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoriaArancelariaId1")
                        .HasColumnType("int");

                    b.Property<string>("CodigoReferencia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Largo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MonedaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<int?>("PaisId1")
                        .HasColumnType("int");

                    b.Property<decimal>("PesoUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UnidadMedida")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaArancelariaId");

                    b.HasIndex("CategoriaArancelariaId1");

                    b.HasIndex("MonedaId");

                    b.HasIndex("PaisId");

                    b.HasIndex("PaisId1");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Proveedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<int>("MonedaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("MonedaId");

                    b.HasIndex("PaisId");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.ResultadoLandedCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CIFTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CantidadTotalImportada")
                        .HasColumnType("int");

                    b.Property<decimal>("CostoTotalImportacion")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FOBTotalLocal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("FOBTotalOriginal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("FechaCalculo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FleteTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MonedaLocalId")
                        .HasColumnType("int");

                    b.Property<int>("OrdenImportacionId")
                        .HasColumnType("int");

                    b.Property<decimal>("PorcentajeITBIS")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PorcentajeTasaServicioAduanal")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("SeguroTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TasaCambioOrden")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalArancel")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalGastosLocales")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalITBIS")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalImpuestoSelectivo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TotalTasaServicioAduanal")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("MonedaLocalId");

                    b.HasIndex("OrdenImportacionId")
                        .IsUnique();

                    b.ToTable("ResultadosLandedCost");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.TasaCambio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaVigencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("MonedaDestinoId")
                        .HasColumnType("int");

                    b.Property<int?>("MonedaId")
                        .HasColumnType("int");

                    b.Property<int>("MonedaOrigenId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorTasa")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("MonedaDestinoId");

                    b.HasIndex("MonedaId");

                    b.HasIndex("MonedaOrigenId");

                    b.ToTable("TasasCambio");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.DetalleOrdenImportacion", b =>
                {
                    b.HasOne("ImportCostPro.Core.Entities.OrdenImportacion", "OrdenImportacion")
                        .WithMany("Detalles")
                        .HasForeignKey("OrdenImportacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Core.Entities.Producto", "Producto")
                        .WithMany("DetallesOrdenImportacion")
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenImportacion");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.DetalleResultadoLandedCost", b =>
                {
                    b.HasOne("ImportCostPro.Core.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Core.Entities.ResultadoLandedCost", "ResultadoLandedCost")
                        .WithMany("Detalles")
                        .HasForeignKey("ResultadoLandedCostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("ResultadoLandedCost");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.GastoImportacion", b =>
                {
                    b.HasOne("ImportCostPro.Core.Entities.Moneda", "Moneda")
                        .WithMany("GastosImportacion")
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Core.Entities.OrdenImportacion", "OrdenImportacion")
                        .WithMany("Gastos")
                        .HasForeignKey("OrdenImportacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moneda");

                    b.Navigation("OrdenImportacion");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Importador", b =>
                {
                    b.HasOne("ImportCostPro.Core.Entities.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.OrdenImportacion", b =>
                {
                    b.HasOne("ImportCostPro.Core.Entities.Importador", "Importador")
                        .WithMany("OrdenesImportacion")
                        .HasForeignKey("ImportadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Core.Entities.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Core.Entities.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Importador");

                    b.Navigation("Moneda");

                    b.Navigation("Proveedor");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Producto", b =>
                {
                    b.HasOne("ImportCostPro.Core.Entities.CategoriaArancelaria", "CategoriaArancelaria")
                        .WithMany()
                        .HasForeignKey("CategoriaArancelariaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Core.Entities.CategoriaArancelaria", null)
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaArancelariaId1");

                    b.HasOne("ImportCostPro.Core.Entities.Moneda", null)
                        .WithMany("Productos")
                        .HasForeignKey("MonedaId");

                    b.HasOne("ImportCostPro.Core.Entities.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Core.Entities.Pais", null)
                        .WithMany("Productos")
                        .HasForeignKey("PaisId1");

                    b.Navigation("CategoriaArancelaria");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Proveedor", b =>
                {
                    b.HasOne("ImportCostPro.Core.Entities.Moneda", "Moneda")
                        .WithMany()
                        .HasForeignKey("MonedaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Core.Entities.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moneda");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.ResultadoLandedCost", b =>
                {
                    b.HasOne("ImportCostPro.Core.Entities.Moneda", "MonedaLocal")
                        .WithMany()
                        .HasForeignKey("MonedaLocalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Core.Entities.OrdenImportacion", "OrdenImportacion")
                        .WithOne("ResultadoOficial")
                        .HasForeignKey("ImportCostPro.Core.Entities.ResultadoLandedCost", "OrdenImportacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MonedaLocal");

                    b.Navigation("OrdenImportacion");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.TasaCambio", b =>
                {
                    b.HasOne("ImportCostPro.Core.Entities.Moneda", "MonedaDestino")
                        .WithMany()
                        .HasForeignKey("MonedaDestinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ImportCostPro.Core.Entities.Moneda", null)
                        .WithMany("TasasCambio")
                        .HasForeignKey("MonedaId");

                    b.HasOne("ImportCostPro.Core.Entities.Moneda", "MonedaOrigen")
                        .WithMany()
                        .HasForeignKey("MonedaOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MonedaDestino");

                    b.Navigation("MonedaOrigen");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.CategoriaArancelaria", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Importador", b =>
                {
                    b.Navigation("OrdenesImportacion");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Moneda", b =>
                {
                    b.Navigation("GastosImportacion");

                    b.Navigation("Productos");

                    b.Navigation("TasasCambio");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.OrdenImportacion", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Gastos");

                    b.Navigation("ResultadoOficial");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Pais", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.Producto", b =>
                {
                    b.Navigation("DetallesOrdenImportacion");
                });

            modelBuilder.Entity("ImportCostPro.Core.Entities.ResultadoLandedCost", b =>
                {
                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
